// File generated by FlutterFire CLI.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHS_uRzatoRRwEKxZlzOjqBxNVAamducM',
    appId: '1:223890689183:web:ed306fff98abe531bca6aa',
    messagingSenderId: '223890689183',
    projectId: 'euphony-btech-3rdyear',
    authDomain: 'euphony-btech-3rdyear.firebaseapp.com',
    storageBucket: 'euphony-btech-3rdyear.firebasestorage.app',
    measurementId: 'G-XW47V8H4FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjQ1OqPP58SqxXj1UTvzJViUuinIDrfac',
    appId: '1:223890689183:android:b660f566d7e7ea50bca6aa',
    messagingSenderId: '223890689183',
    projectId: 'euphony-btech-3rdyear',
    storageBucket: 'euphony-btech-3rdyear.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0fPHxzSuEBGao38ZLSzTET6NJy-yMob8',
    appId: '1:223890689183:ios:5f9691c7a6720431bca6aa',
    messagingSenderId: '223890689183',
    projectId: 'euphony-btech-3rdyear',
    storageBucket: 'euphony-btech-3rdyear.firebasestorage.app',
    iosBundleId: 'com.example.musicapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0fPHxzSuEBGao38ZLSzTET6NJy-yMob8',
    appId: '1:223890689183:ios:5f9691c7a6720431bca6aa',
    messagingSenderId: '223890689183',
    projectId: 'euphony-btech-3rdyear',
    storageBucket: 'euphony-btech-3rdyear.firebasestorage.app',
    iosBundleId: 'com.example.musicapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHS_uRzatoRRwEKxZlzOjqBxNVAamducM',
    appId: '1:223890689183:web:a5945e3b7b23a0acbca6aa',
    messagingSenderId: '223890689183',
    projectId: 'euphony-btech-3rdyear',
    authDomain: 'euphony-btech-3rdyear.firebaseapp.com',
    storageBucket: 'euphony-btech-3rdyear.firebasestorage.app',
    measurementId: 'G-45L3KVZZKK',
  );
}
